### ISSUE TITLE
'MIPI_DISPLAY_PIN_POWER' undeclared

### ISSUE THREAD

**Issue by eugnio1** [tuupola/hagl_pico_mipi#34]
<img width="1273" alt="Screenshot 2023-02-24 at 4 42 38 PM" src="https://user-images.githubusercontent.com/125184176/221133028-107002d3-ad09-455c-9b87-f8ee24a54c74.png">
mipi_display.c is quite new
And how to use the load image cmd 
<img width="1280" alt="Screenshot 2023-02-24 at 4 41 41 PM" src="https://user-images.githubusercontent.com/125184176/221133209-c421a7fd-1928-43a6-927a-f732e9a29ad1.png">
I'm using a 160*128 st7735 display

**Comment by tuupola** [comment]
It seems I should add a default value for it. In the meanwhile if you are not using power pin declare it in your config as:

```
target_compile_definitions(firmware PRIVATE
  MIPI_DISPLAY_PIN_POWER=-1
)
```

**Comment by tuupola** [comment]
Fixed in master. Thanks!
