### ISSUE TITLE
MIPI_DISPLAY_INVERT setting has no effect

### ISSUE THREAD

**Issue by tuupola** [tuupola/hagl_pico_mipi#60]
Currently the `MIPI_DISPLAY_INVERT` has no effect because it is always defined and code checks only `#ifdef` and not the value.

See https://github.com/tuupola/pico_effects/issues/10

**Comment by gamemake-eng** [comment]
Just in case you forgot, turns out someone has already made a PR trying to fix the issue.

https://github.com/tuupola/hagl_pico_mipi/pull/53

**Comment by tuupola** [comment]
Fixed via https://github.com/tuupola/hagl_pico_mipi/pull/53
