### ISSUE TITLE
HAGL & Pi Pico + ILI9341

### ISSUE THREAD

**Issue by sudni** [tuupola/hagl_pico_mipi#67]
Hi, thank you for the great job! I test version with SDL2 on my linux machine and I was impressed by the result. Now I wanted to try the Pi Pico version with a tft ILI9341 screen, I chose the cmake file : generic-ili9341-320x240.cmake, and nothing appears. I checked my wiring with a quick code in micropython and everything works. Is there a limitation due to the use of a mipi driver?

**Comment by tuupola** [comment]
ILI9341 is a MIPI DCS chip so it is supported. I would double check the wiring. How does your MicroPython code look like?

**Comment by sudni** [comment]
Thank you for the feedback, my driver reference for micropython is https://github.com/rdagger/micropython-ili9341/blob/master/ili9341.py
MISO Pin not connected. And the setup 
    # Baud rate of 40000000 seems about the max
    spi = SPI(1, baudrate=40000000, sck=Pin(10), mosi=Pin(11))
    display = Display(spi, dc=Pin(8), cs=Pin(9), rst=Pin(12))
just the SPI bus a little slower .
I tried changing the speed in your driver, but without success.

**Comment by tuupola** [comment]
Is the backlight pin setting correct? If backlight is off you might get a black screen.

**Comment by sudni** [comment]
Hello, yes backlight Pin is connected on Vcc. In boot screen is light and just after screen becomes blacks. 
I compile in debug version to to view debug info

[main] 251588 total heap                                                                         
[main] 251588 free heap                                                                          
[HAGL HAL] Initialising single buffered display.                                                 
[HAGL HAL] Initialising SPI.                                                                     
[HAGL HAL] Baudrate is set to 62500000.
[HAGL HAL] clk_peri 125000000.
[HAGL HAL] clk_sys 125000000.

[main] 251588 total heap 
[main] 251588 free heap 
[HAGL HAL] Initialising single buffered display.
[HAGL HAL] Initialising SPI.
[HAGL HAL] Baudrate is set to 31250000.
[HAGL HAL] clk_peri 125000000.
[HAGL HAL] clk_sys 125000000.

first try with default baud rate and second at same baud like in python code.

**Comment by tuupola** [comment]
Sounds like backlight is on and then something turns it off? I don't know how your code looks like, but you could try with: 

https://github.com/tuupola/pico_effects

You probably can just use the generic ILI9341 config, again assuming that the pins are correct.

https://github.com/tuupola/pico_effects/blob/master/CMakeLists.txt#L66

Also if you have 320x240 screen change `PIXEL_SIZE` to `2` or you will run out of memory. You could actually try this with your own test program too. Maybe you are running out of memory.

https://github.com/tuupola/pico_effects/blob/master/CMakeLists.txt#L52

**Comment by sudni** [comment]
Great!! I succeeded in getting your demo to work!
There's nothing like a grey, damp Sunday to spend some time coding and debugging.
You were right, I've rewired everything and it works.
Thanks again for your support and for taking the time to reply.

**Comment by sudni** [comment]
oups just I also had to set PIXEL_SIZE to 2 for it to work, as you asked me to do

**Comment by tuupola** [comment]
Great :)
